FROM golang:1.16-alpine as build-stage

WORKDIR /usr/src/app

COPY . .

run go build

FROM alpine

EXPOSE 8080

WORKDIR /usr/src/app

COPY --from=build-stage /usr/src/app/server /usr/src/app/server

RUN adduser -D appuser && \
    chown appuser /usr/src/app

ENV PORT=8080

USER appuser

CMD ["./server"]