FROM golang:1.16

ENV PORT=8080
ENV REQUEST_ORIGIN=http://localhost

EXPOSE ${PORT}

WORKDIR /usr/src/app

COPY . .

RUN go build

RUN useradd -m appuser
RUN chown appuser /usr/src/app 

USER appuser

CMD ./server