version: "3.8"

services:
  redis:
    image: redis
    ports: 
    - 6379:6379
  frontend:
    build: ./example-frontend
    image: frontend
    ports:
      - 5000:5000
  backend:
    build: ./example-backend
    image: backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis