version: "3.8"

services:
  pgsql:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: thisIsPassword
    container_name: db_pgsql
    volumes:
     - database:/var/lib/postgresql/data
  redis:
    image: redis
    restart: unless-stopped
    ports: 
      - 6379:6379
  frontend:
    build: ./example-frontend 
    ports:
      - 5000:5000
  backend:
    build: ./example-backend 
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=pgsql
      - POSTGRES_PASSWORD=thisIsPassword
  reverse_proxy:
    image: nginx:1.19-alpine
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    environment:
      - NGINX_PORT=80

volumes:
  database: